### YamlMime:TSType
name: IDynamicDataSharedSourceConfiguration
uid: '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration:interface'
package: '@microsoft/sp-property-pane!'
fullName: IDynamicDataSharedSourceConfiguration
summary: Configuration related to a shared source.
remarks: ''
example: []
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: filters
    uid: '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration#filters:member'
    package: '@microsoft/sp-property-pane!'
    fullName: filters
    summary: Filters for the shared source.
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'filters?: IDynamicDataSharedSourceFilters;'
      return:
        type: '<xref uid="@microsoft/sp-property-pane!IDynamicDataSharedSourceFilters:interface" />'
  - name: sourcesLabel
    uid: '@microsoft/sp-property-pane!IDynamicDataSharedSourceConfiguration#sourcesLabel:member'
    package: '@microsoft/sp-property-pane!'
    fullName: sourcesLabel
    summary: |-
      User-friendly, localized label for the sources dropdown.

      default value - 'Connect to source'
    remarks: ''
    example: []
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'sourcesLabel?: string;'
      return:
        type: string
