### YamlMime:TSType
name: IImageCardViewConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!IImageCardViewConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: IImageCardViewConfiguration
summary: Configuration for an Image Card view.
remarks: >-
  The Image Card view displays the following: - Card title - Card icon - One image - One primary text field - Zero
  buttons in the `Medium` Card size, up to two buttons in `Large` Card size
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: footer
    uid: '@microsoft/sp-adaptive-card-extension-base!IImageCardViewConfiguration#footer:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: footer
    summary: Footer area components.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'footer: GenericCardViewFooterConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!GenericCardViewFooterConfiguration:type" />'
  - name: header
    uid: '@microsoft/sp-adaptive-card-extension-base!IImageCardViewConfiguration#header:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: header
    summary: Header area components.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'header: ICardTextConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardTextConfiguration:interface" />'
  - name: image
    uid: '@microsoft/sp-adaptive-card-extension-base!IImageCardViewConfiguration#image:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: image
    summary: Image displayed on the card.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'image: IAdaptiveCardExtensionImage;'
      return:
        type: '<xref uid="@microsoft/sp-adaptive-card-extension-base!IAdaptiveCardExtensionImage:interface" />'
extends: 'Omit&lt;<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardViewConfiguration:interface" />, ''body''&gt;'
