### YamlMime:TSType
name: ILineChartCardViewConfiguration
uid: '@microsoft/sp-adaptive-card-extension-base!ILineChartCardViewConfiguration:interface'
package: '@microsoft/sp-adaptive-card-extension-base!'
fullName: ILineChartCardViewConfiguration
summary: Configuration for a line chart card view.
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: body
    uid: '@microsoft/sp-adaptive-card-extension-base!ILineChartCardViewConfiguration#body:member'
    package: '@microsoft/sp-adaptive-card-extension-base!'
    fullName: body
    summary: Body area components.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: >-
        body: ICardLineChartConfiguration<T> | [ICardLineChartConfiguration<T>] | [ICardTextConfiguration,
        ICardLineChartConfiguration<T>];
      return:
        type: >-
          <xref uid="@microsoft/sp-adaptive-card-extension-base!ICardLineChartConfiguration:interface" />&lt;T&gt; |
          [<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardLineChartConfiguration:interface" />&lt;T&gt;] |
          [<xref uid="@microsoft/sp-adaptive-card-extension-base!ICardTextConfiguration:interface" />, <xref
          uid="@microsoft/sp-adaptive-card-extension-base!ICardLineChartConfiguration:interface" />&lt;T&gt;]
extends: '<xref uid="@microsoft/sp-adaptive-card-extension-base!IDataVisualizationCardViewConfiguration:interface" />'
