### YamlMime:TSType
name: IAadHttpClientConfiguration
uid: '@microsoft/sp-http-base!IAadHttpClientConfiguration:interface'
package: '@microsoft/sp-http-base!'
fullName: IAadHttpClientConfiguration
summary: Flags interface for HttpClientConfiguration.
remarks: ''
isPreview: false
isDeprecated: false
type: interface
extends: '<xref uid="@microsoft/sp-http-base!IHttpClientConfiguration:interface" />'
