### YamlMime:TSType
name: IHttpClientConfiguration
uid: '@microsoft/sp-http-base!IHttpClientConfiguration:interface'
package: '@microsoft/sp-http-base!'
fullName: IHttpClientConfiguration
summary: Flags interface for HttpClientConfiguration.
remarks: ''
isPreview: false
isDeprecated: false
type: interface
