### YamlMime:TSType
name: ISPHttpClientConfigurations
uid: '@microsoft/sp-http-base!ISPHttpClientConfigurations:interface'
package: '@microsoft/sp-http-base!'
fullName: ISPHttpClientConfigurations
summary: Standard configurations for SPHttpClient.
remarks: >-
  This interface provides standard predefined SPHttpClientConfiguration objects for use with the SPHttpClient class. In
  general, clients should choose the latest available version number, which enables all the switches that are
  recommended for typical scenarios. (If new switches are introduced in the future, a new version number will be
  introduced, which ensures that existing code will continue to function the way it did at the time when it was tested.)
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: v1
    uid: '@microsoft/sp-http-base!ISPHttpClientConfigurations#v1:member'
    package: '@microsoft/sp-http-base!'
    fullName: v1
    summary: >-
      Version 1 enables these switches:


      consoleLogging = true; jsonRequest = true; jsonResponse = true; defaultSameOriginCredentials = true;
      defaultODataVersion = ODataVersion.v4; requestDigest = true
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'readonly v1: SPHttpClientConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-http-base!SPHttpClientConfiguration:class" />'
