### YamlMime:TSType
name: ISPHttpClientBatchConfigurations
uid: '@microsoft/sp-http-base!ISPHttpClientBatchConfigurations:interface'
package: '@microsoft/sp-http-base!'
fullName: ISPHttpClientBatchConfigurations
summary: Standard configurations for SPHttpClient.
remarks: >-
  This interface provides standard predefined SPHttpClientBatchConfiguration objects for use with the SPHttpClientBatch
  class. In general, clients should choose the latest available version number, which enables all the switches that are
  recommended for typical scenarios. (If new switches are introduced in the future, a new version number will be
  introduced, which ensures that existing code will continue to function the way it did at the time when it was tested.)
isPreview: true
isDeprecated: false
type: interface
properties:
  - name: v1
    uid: '@microsoft/sp-http-base!ISPHttpClientBatchConfigurations#v1:member'
    package: '@microsoft/sp-http-base!'
    fullName: v1
    summary: 'Version 1 enables these switches: consoleLogging = true; jsonRequest = true; jsonResponse = true'
    remarks: ''
    isPreview: true
    isDeprecated: false
    syntax:
      content: 'readonly v1: SPHttpClientBatchConfiguration;'
      return:
        type: '<xref uid="@microsoft/sp-http-base!SPHttpClientBatchConfiguration:class" />'
