### YamlMime:TSType
name: Environment
uid: '@microsoft/sp-core-library!Environment:class'
package: '@microsoft/sp-core-library!'
fullName: Environment
summary: Information about the system environment where the SharePoint Framework is running.
remarks: ''
isPreview: false
isDeprecated: false
type: class
properties:
  - name: type
    uid: '@microsoft/sp-core-library!Environment.type:member'
    package: '@microsoft/sp-core-library!'
    fullName: type
    summary: Indicates the general type of environment where the SharePoint Framework is running.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'static get type(): EnvironmentType;'
      return:
        type: '<xref uid="@microsoft/sp-core-library!EnvironmentType:enum" />'
