### YamlMime:TSType
name: IDynamicDataSharedPropertyConfiguration
uid: '@microsoft/sp-webpart-base!IDynamicDataSharedPropertyConfiguration:interface'
package: '@microsoft/sp-webpart-base!'
fullName: IDynamicDataSharedPropertyConfiguration
summary: Configuration related to a shared property.
remarks: We have left the original implementation here to avoid breaking the public API contract.
isPreview: false
isDeprecated: true
customDeprecatedMessage: >-
  This is obsolete now. This interface has been moved to `@microsoft/sp-property-pane`<!-- -->. Please consume it from
  there.
type: interface
extends: '<xref uid="@microsoft/sp-property-pane!IDynamicDataSharedPropertyConfiguration:interface" />'
